### ISSUE TITLE
More Rock and Metal lists

### ISSUE THREAD

**Issue by foordeluxe** [clem9669/wordlists#15]
I'm stuck at cracking a list and it full of Rock and Metal albums. I just wonder if you could maybe generate all Rock Albums and Metal Albums that exist? Tracks too if it's possible from last.fm (With space, without space and so on).   I saw you made a code to fetch the toplists only.

Your lists is really good, I got nice hit's with them. And I'm a happy user to use your list. The only downside is a lot of FR lists and not many English versions. Anyway thanks so much for your job you do.

**Comment by clem9669** [comment]
Hi @foordeluxe 

Sorry for the delay, I was away and will be again. 🙁 
I will make a more complete version of music (including albums, songs, artists, ...) ! 🎵 

Haha thanks 😍 
I know but I want to specialize in FR list since I know French better ^^

**Comment by clem9669** [comment]
Hi @foordeluxe, 

I have push a new bot which use Spotify chart and Japanese plateform music site.
The bot commit to **artists, songs & albums** based on top 50 daily (*Wordwide, FR, BE, CH*).

The parsing is not that good. It will work on it later but at least any password based on top song, artist or album name shoud be a hit 😉
