### ISSUE TITLE
é and è characters.

### ISSUE THREAD

**Issue by Privacy6484847** [clem9669/wordlists#20]
é and è charachters are printed like this on hashcat any fix?: Th├⌐auJean

**Comment by clem9669** [comment]
Hi,
Is it from a list or the release ?

**Comment by Privacy6484847** [comment]
Thanks for the reply. It's from the release 21 and 22.

**Comment by Privacy6484847** [comment]
Yup it definitely worked: 7a596db12cab70abc6201cfcea8137dc:Th├⌐auJean
So yes it's just a hashcat printing issue.
Well done.

**Comment by Privacy6484847** [comment]
What do you use to edit and manage your wordlists? :)

**Comment by clem9669** [comment]
To edit, i use SublimeText or EmEditor when the file is too big :)

**Comment by Privacy6484847** [comment]
I tried EmEditor. Do you know how to delete words lower than for example 6 characters?

**Comment by clem9669** [comment]
I recommand using awk: https://linux.die.net/man/1/awk

`awk 'length > 72' file // prints lines that are longer than 72 characters`
