### ISSUE TITLE
The command does not work

### ISSUE THREAD

**Issue by Sylvain-27** [clem9669/wordlists#23]
The command does not work

LC_ALL=C.UTF-8; sort -u wordlist >> wordlist_uniq_sorted

and returns an error
"sort: cannot read: wordlist: No such file or folder"

**Comment by clem9669** [comment]
Hi @Sylvain-27 ,

The command should not be used as is. 
It should be customized and the 7zip inside the repo will trash outputed wordlist.

Therefore, you should un7zip and select what matter to you then deduplicate.
